"""init

Revision ID: 51703ac9fd0d
Revises: 
Create Date: 2022-12-04 14:11:18.223709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51703ac9fd0d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatdata',
    sa.Column('id', sa.String(length=256), nullable=False),
    sa.Column('videoId', sa.String(length=64), nullable=False),
    sa.Column('name', sa.Unicode(length=64), nullable=True),
    sa.Column('channelId', sa.String(length=200), nullable=False),
    sa.Column('chatType', sa.String(length=64), nullable=True),
    sa.Column('timeStamp', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('message', sa.Unicode(length=512), nullable=True),
    sa.Column('amountValue', sa.Integer(), nullable=False),
    sa.Column('amountString', sa.String(length=64), nullable=True),
    sa.Column('currency', sa.String(length=64), nullable=True),
    sa.Column('isVerified', sa.Boolean(), nullable=True),
    sa.Column('isOwner', sa.Boolean(), nullable=True),
    sa.Column('isSponsor', sa.Boolean(), nullable=True),
    sa.Column('isModerator', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'videoId')
    )
    op.create_table('videodata',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('channelId', sa.String(length=200), nullable=False),
    sa.Column('title', sa.Unicode(length=256), nullable=True),
    sa.Column('description', sa.Unicode(length=5192), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('isLive', sa.Boolean(), nullable=True),
    sa.Column('hasLiveChat', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videodata')
    op.drop_table('chatdata')
    # ### end Alembic commands ###
